# Generated by Django 4.1.5 on 2023-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(choices=[('Store', 'Store'), ('Deployed', 'Deployed')], default='Deployed', max_length=20),
        ),
    ]
