# Generated by Django 4.2.2 on 2023-07-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="station",
            new_name="department",
        ),
    ]
